module.exports = {

    // Success
    SUCCESS : { "isSuccess": true, "code": 200, "message":"요청에 성공하였습니다." },

    // Common
    TOKEN_EMPTY : { "isSuccess": false, "code": 388, "message":"JWT 토큰을 입력해주세요." },
    TOKEN_VERIFICATION_FAILURE : { "isSuccess": false, "code": 389, "message":"유효하지 않은 JWT토큰입니다." },
    TOKEN_VERIFICATION_SUCCESS : { "isSuccess": true, "code": 200, "message":"JWT 토큰 검증 성공" }, // ?

    //Request error
    SIGNUP_ID_EMPTY : { "isSuccess": false, "code": 301, "message":"ID를 입력해주세요." },
    SIGNUP_PASSWORD_EMPTY : { "isSuccess": false, "code": 302, "message":"비밀번호를 입력해주세요." },
    SIGNUP_LOGOURL_EMPTY : { "isSuccess": false, "code": 303, "message":"로고 이미지를 입력해주세요." },
    SIGNUP_COMPANYNAME_EMPTY : { "isSuccess": false, "code": 304, "message":"회사명을 입력해주세요." },
    SIGNUP_COMPANYNUM_EMPTY : { "isSuccess": false, "code": 305, "message":"법인번호를 입력해주세요." },
    SIGNUP_ADDRESS_EMPTY : { "isSuccess": false, "code": 306, "message":"회사 주소를 입력해주세요." },
    SIGNUP_COMPANYPHONE_EMPTY : { "isSuccess": false, "code": 307, "message":"회사 전화번호를 입력해주세요." },
    SIGNUP_EMAIL_EMPTY : { "isSuccess": false, "code": 308, "message":"회사 이메일을 입력해주세요." },
    SIGNUP_ADMINNAME_EMPTY : { "isSuccess": false, "code": 309, "message":"관리자 이름을 입력해주세요." },
    SIGNUP_ADMINPHONE_EMPTY : { "isSuccess": false, "code": 310, "message":"관리자 전화번호를 입력해주세요." },
    SIGNUP_WORK_EMPTY : { "isSuccess": false, "code": 311, "message":"업종을 입력해주세요." },
    SIGNUP_LINK_EMPTY : { "isSuccess": false, "code": 312, "message":"홈페이지 링크를 입력해주세요." },
    SIGNUP_EMAIL_ERROR_TYPE : { "isSuccess": false, "code": 313, "message":"이메일을 형식을 정확하게 입력해주세요." },
    SIGNUP_URL_ERROR_TYPE : { "isSuccess": false, "code": 314, "message":"URL 형식을 정확하게 입력해주세요." },
    SIGNUP_PHONE_ERROR_TYPE : { "isSuccess": false, "code": 315, "message":"전화번호 형식을 정확하게 입력해주세요." },
    SIGNUP_ACCOUNT_ERROR_TYPE : { "isSuccess": false, "code": 318, "message":"계좌번호 형식을 정확하게 입력해주세요." },
    SIGNUP_ADMINPHONE_ERROR_TYPE : { "isSuccess": false, "code": 316, "message":"관리자 전화번호 형식을 정확하게 입력해주세요." },
    SIGNUP_LINK_ERROR_TYPE : { "isSuccess": false, "code": 319, "message":"홈페이지 형식을 정확하게 입력해주세요." },
    SIGNUP_EMAIL_FAIL : { "isSuccess": false, "code": 317, "message":"중복된 이메일입니다." },
    SIGNUP_AUTH_ERROR : { "isSuccess": false, "code": 319, "message":"인증에 실패하였습니다." },
    SIGNUP_SERVER_ERROR : { "isSuccess": false, "code": 406, "message":"인증 서버 에러입니다." },
    SIGNUP_NAME_FAIL : { "isSuccess": false, "code": 318, "message":"중복된 ID입니다." },
    SIGNUP_UPPASSWORD_EMPTY : { "isSuccess": false, "code": 322, "message":"변경할 패스워드를 입력해주세요." },
    SIGNUP_DEPARTMENT_EMPTY : { "isSuccess": false, "code": 323, "message":"부서를 입력해주세요." },
    SIGNUP_POSITION_EMPTY : { "isSuccess": false, "code": 324, "message":"직책을 입력해주세요." },
    SIGNUP_DEPARTMENT_ALREADY : { "isSuccess": false, "code": 325, "message":"해당 부서에 이 직책이 이미 존재합니다." },
    SIGNUP_DEPARTMENT_NONE : { "isSuccess": false, "code": 326, "message":"해당 부서는 존재하지 않습니다." },
    SIGNUP_POSITION_NONE : { "isSuccess": false, "code": 327, "message":"해당 부서에 직책이 존재하지 않습니다." },
    SIGNUP_DEPARTMENT_USE : { "isSuccess": false, "code": 328, "message":"해당 부서에 사원이 존재해 삭제할 수 없습니다." },
    SIGNUP_POSITION_USE : { "isSuccess": false, "code": 329, "message":"해당 직책에 사원이 존재해 삭제할 수 없습니다." },
    SIGNUP_GENDER_EMPTY : { "isSuccess": false, "code": 331, "message":"성별을 입력해주세요." },
    SIGNUP_AGE_EMPTY : { "isSuccess": false, "code": 332, "message":"나이 입력해주세요." },
    SIGNUP_MEMBERPHONE_EMPTY : { "isSuccess": false, "code": 333, "message":"사원의 전화번호를 입력해주세요." },
    SIGNUP_MEMBERADDRESS_EMPTY : { "isSuccess": false, "code": 334, "message":"사원의 주소를 입력해주세요." },
    SIGNUP_MEMBEREMAIL_EMPTY : { "isSuccess": false, "code": 335, "message":"사원의 이메일을 입력해주세요." },
    SIGNUP_MEMBERACCOUNT_EMPTY : { "isSuccess": false, "code": 336, "message":"사원의 계좌번호 입력해주세요." },
    SIGNUP_NICKNAME_USE : { "isSuccess": false, "code": 337, "message":"중복된 닉네임입니다." },
    SIGNNAME_USE : { "isSuccess": false, "code": 338, "message":"중복된 닉네입입니다." },
    SIGAME_USE : { "isSuccess": false, "code": 339, "message":"중복된 닉네입입니다." },
    SIGNUP_NAME_ALREADY : { "isSuccess": false, "code": 340, "message":"중복된 회사명입니다." },
    SIGNUP_MEMBER_WRONG : { "isSuccess": false, "code": 341, "message":"존재하지 않는 사용자입니다." },
    SIGNUP_MEMBER_OUT : { "isSuccess": false, "code": 346, "message":"퇴사 신청한 회원이 아닙니다." },
    SIGNUP_GIFTIMG_EMPTY : { "isSuccess": false, "code": 347, "message":"기프트 이미지를 입력해주세요." },
    SIGNUP_GIFTNAME_EMPTY : { "isSuccess": false, "code": 348, "message":"기프트 이름을 입력해주세요." },
    SIGNUP_GIFTINFO_EMPTY : { "isSuccess": false, "code": 349, "message":"기프트 정보를 입력해주세요." },
    SIGNUP_GIFTRULE_EMPTY : { "isSuccess": false, "code": 350, "message":"기프트 규칙을 입력해주세요." },
    SIGNUP_GIFTRULE_ALREADY : { "isSuccess": false, "code": 351, "message":"중복된 기프트명입니다." },
    SIGNUP_GIFTID_NONE : { "isSuccess": false, "code": 352, "message":"해당 기프트는 존재하지 않습니다." },
    SIGNUP_GIFTLOG_NONE : { "isSuccess": false, "code": 354, "message":"해당 기프트 신청은 존재하지 않습니다." },
    SIGNUP_GIFTLOG_STATUS : { "isSuccess": false, "code": 355, "message":"해당 기프트 신청은 승인대기 상태가 아닙니다." },
    SIGNUP_GIFTLOGIDX_EMPTY : { "isSuccess": false, "code": 356, "message":"기프트 신청 idx를 입력해주세요." },
    SIGNUP_GIFTLOGCODE_EMPTY : { "isSuccess": false, "code": 357, "message":"승인 코드를 입력해주세요." },
    SIGNUP_GIFTLOGCODE_TYPE : { "isSuccess": false, "code": 358, "message":"승인 코드를 올바른 형식으로 입력해주세요." },
    SIGNUP_GIFTARRAY_TYPE : { "isSuccess": false, "code": 359, "message":"변경 옵션을 리스트 형식으로 입력해주세요." },
    SIGNUP_DATE_EMPTY : { "isSuccess": false, "code": 360, "message":"날짜를 입력해주세요." },
    SIGNUP_DATE_TYPE : { "isSuccess": false, "code": 361, "message":"날짜 형식을 지켜주세요." },
    SIGNUP_MEMBER_NONE : { "isSuccess": false, "code": 362, "message":"해당 사원은 존재하지 않습니다." },
    SIGNUP_ID_TYPE : { "isSuccess": false, "code": 363, "message":"ID 형식이 올바르지 않습니다." },
    SIGNUP_NUMBER_TYPE : { "isSuccess": false, "code": 364, "message":"사업자 등록번호가 올바르지 않습니다." },
    SIG_PAGE_NONE : { "isSuccess": false, "code": 365, "message":"리스트 페이지를 입력하세요." },
    SIG_PAGE_WRONG : { "isSuccess": false, "code": 366, "message":"해당 페이지는 존재하지 않습니다." },
    SIG_MONTH_TYPE : { "isSuccess": false, "code": 367, "message":"월별 필터 형식을 지켜주세요." },
    SIG_LOG_WRONG : { "isSuccess": false, "code": 368, "message":"해당 신청은 아직 증빙되지 않았습니다." },
    SIGNUP_COMPANY_WRONG : { "isSuccess": false, "code": 377, "message":"탈퇴한 회사입니다." },
    SIGNUP_DELOPT_EMPTY : { "isSuccess": false, "code": 378, "message":"삭제 옵션을 입력해주세요." },
    SIGNUP_UPOPT_EMPTY : { "isSuccess": false, "code": 379, "message":"변경 옵션을 입력해주세요." },
    SIGNUP_ADMIN_WRONG : { "isSuccess": false, "code": 390, "message":"현재 회사의 관리자가 아닙니다." },
    
    SIGNIN_ID_WRONG : { "isSuccess": false, "code": 320, "message": "존재하지 않는 관리자입니다." },
    SIGNIN_PASSWORD_WRONG : { "isSuccess": false, "code": 321, "message": "비밀번호가 잘못 되었습니다." },
    SIGNIN_COMPANY_WRONG : { "isSuccess": false, "code": 370, "message": "존재하지 않는 회사입니다." },
    SIGNIN_INACTIVE_ACCOUNT : { "isSuccess": false, "code": 3005, "message": "신고당한 계정입니다. 고객센터에 문의해주세요." },
    SIGNIN_WITHDRAWAL_ACCOUNT : { "isSuccess": false, "code": 3006, "message": "탈퇴 된 계정입니다. 고객센터에 문의해주세요." },

    //Connection, Transaction 등의 서버 오류
    DB_ERROR : { "isSuccess": false, "code": 409, "message": "데이터 베이스 에러"},
    SERVER_ERROR : { "isSuccess": false, "code": 404, "message": "네트워크 오류가 발생했습니다."},


}
